In [4]:
import requests
import numpy as np

# URL of the HARNet10 prediction API
API_URL = "http://localhost:8000/predict"

# Function to send one data window and print the result
def send_request(data_window: np.ndarray):
    payload = {"data": data_window.tolist()}
    response = requests.post(API_URL, json=payload)
    if response.ok:
        print("Input first 3 samples:", data_window[:3])
        print("Predicted activity:", response.json()["activity"])
    else:
        print("Error:", response.status_code, response.text)

if __name__ == "__main__":
    # 1. Low-amplitude noise (simulate static)
    static_data = np.random.normal(0, 0.01, (300, 3))
    # 2. High-amplitude noise (simulate vigorous motion)
    active_data = np.random.normal(0, 1.0, (300, 3))
    # 3. Sinusoidal pattern (simulate periodic walking)
    t = np.linspace(0, 10, 300)
    walk_data = np.stack([
        0.5 * np.sin(2 * np.pi * 1 * t),
        0.5 * np.sin(2 * np.pi * 1 * t + np.pi/2),
        0.5 * np.sin(2 * np.pi * 1 * t + np.pi)
    ], axis=1)

    # Send each window
    for window in [static_data, active_data, walk_data]:
        send_request(window)


Input first 3 samples: [[-0.01495561 -0.00577472 -0.00362186]
 [-0.0150432  -0.00670709  0.0019731 ]
 [ 0.00371593  0.01776455 -0.00425767]]
Predicted activity: 1
Input first 3 samples: [[-0.53142123 -0.60678189  0.20593821]
 [ 2.29066217  1.29327426  1.42500368]
 [-0.07616856  0.00779166  0.47847183]]
Predicted activity: 3
Input first 3 samples: [[ 0.00000000e+00  5.00000000e-01  6.12323400e-17]
 [ 1.04298400e-01  4.89000863e-01 -1.04298400e-01]
 [ 2.04008030e-01  4.56487375e-01 -2.04008030e-01]]
Predicted activity: 1
