In [6]:
!ls

 binary_image.jpg  'image (1).jpg'  'image (2).jpg'  'image (5).jpg'   sample_data


In [ ]:
import cv2

# Path to the downloaded video file
video_path = 'Vid.mp4'  # Update the path to your video file

# Initialize video capture object
cap = cv2.VideoCapture(video_path)

# Check if video file is opened successfully
if not cap.isOpened():
    print("Error: Unable to open video file.")
else:
    # Read and display frames from the video
    while True:
        ret, frame = cap.read()

        if ret:
            # Display the frame
            cv2.imshow('Video', frame)

            # Check if the user pressed 'q' to exit
            if cv2.waitKey(25) & 0xFF == ord('q'):
                break
        else:
            break

    # Release the video capture object and close OpenCV windows
    cap.release()
    cv2.destroyAllWindows()


In [5]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Load the first image in grayscale
img_gray = cv2.imread('image (1).jpg', cv2.IMREAD_GRAYSCALE)

# Load the second image in color
img_color = cv2.imread('image (5).jpg')

# Convert the second image into grayscale
img_color_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)

# Print the pixel values of the grayscale image
print("Pixel values of the grayscale image:")
print(img_gray)

# Convert the grayscale image into a binary image
_, binary_image = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY)

# Save the binary image
cv2.imwrite('binary_image.jpg', binary_image)


Pixel values of the grayscale image:
[[ 6  0 11 ... 14  5  0]
 [ 5  2  0 ...  0  6  0]
 [ 0  4 58 ... 31  7  1]
 ...
 [ 3  0 56 ... 45  6  1]
 [10  0  2 ... 86  4  0]
 [ 4  5  0 ...  4  2  0]]


True

In [15]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
# Load the image in OpenCV and check the size
image = cv2.imread('image (1).jpg')
print("Image size:", image.shape)

# Convert the image into grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# save the grayscale image
cv2.imwrite('Grayscale Image.jpg', gray_image)

# Display the pixel values of the grayscale image
print("Pixel values of the grayscale image:")
print(gray_image)

# Load the image in binary
binary_image = cv2.imread('image (1).jpg', cv2.IMREAD_GRAYSCALE)

# Swap the black (0) and white (255) pixels
swapped_image = cv2.bitwise_not(binary_image)
# Check if the swapped image is not empty
if not swapped_image is None:
    # Save the swapped image
    cv2.imwrite('swapped_image.jpg', swapped_image)
else:
    print("Swapped image is empty. Check your code.")


Image size: (136, 130, 3)
Pixel values of the grayscale image:
[[ 6  0 11 ... 14  5  0]
 [ 5  2  0 ...  0  6  0]
 [ 0  4 58 ... 31  7  1]
 ...
 [ 3  0 56 ... 45  6  1]
 [10  0  2 ... 86  4  0]
 [ 4  5  0 ...  4  2  0]]
